//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kur2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_List
    {
        public int ProductID { get; set; }
        public string Group { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
